# Generated by Django 5.0.7 on 2024-07-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_admin_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
