# Generated by Django 5.0.7 on 2024-07-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='application_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
