# Generated by Django 5.0.7 on 2024-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_phone_number'),
        ('admin_api', '0003_alter_category_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='admin_api.category'),
        ),
    ]
