# Generated by Django 5.0.7 on 2024-08-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chaptermarker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterMarker',
        ),
    ]
